[project]
name = "22-sessions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "google-genai>=1.56.0",
    "openai-agents[sqlalchemy]>=0.6.4",
    "psycopg2-binary>=2.9.11",
]
